version: '3.9'
services:
  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: togeeat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d togeeat -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_DURATION: ${JWT_ACCESS_TOKEN_DURATION}
      ALLOWED_IMAGE_MIME_TYPES: ${ALLOWED_IMAGE_MIME_TYPES}
      DEFAULT_MAX_IMAGE_SIZE: ${DEFAULT_MAX_IMAGE_SIZE}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/sh -c "yarn --cwd /app prisma migrate deploy && node /app/dist/src/main.js"