import { PrismaClient } from "@prisma/client";

export default async function seedHobby(prisma: PrismaClient) {
  await prisma.hobby.createMany({
    data: [
      { name: "観光" },
      { name: "本を読む" },
      { name: "音楽を聴く" },
      { name: "スポーツをする（サッカー）" },
      { name: "スポーツをする（バスケットボール）" },
      { name: "スポーツをする（バレーボール）" },
      { name: "スポーツをする（テニス）" },
      { name: "映画を見る" },
      { name: "運動をする" },
      { name: "ヨガ" },
      { name: "写真を撮る" },
      { name: "サーフィン" },
      { name: "料理を学ぶ" },
      { name: "楽器（ギター）を演奏する" },
      { name: "楽器（ピアノ）を演奏する" },
      { name: "楽器（ドラム）を演奏する" },
      { name: "カラオケを歌う" },
      { name: "ビデオゲームをする" },
      { name: "チェスをする" },
      { name: "ビリヤード" },
      { name: "ボウリングをする" },
      { name: "卓球をする" },
      { name: "模範的な建築家になる" },
      { name: "ゴルフをする" },
      { name: "バドミントンをしている" },
      { name: "ペットの世話をする" },
      { name: "武道（空手）" },
      { name: "武道（テコンドー）の練習" },
      { name: "武道（柔道）の練習" },
      { name: "野球をする" },
      { name: "テニスをしている" },
      { name: "ハンドボールをする" },
      { name: "水泳で遊ぶ" },
      { name: "テニスをする" },
      { name: "樽の上でライオンを作る" },
      { name: "外国語を学ぶ" },
      { name: "サッカーをする" },
      { name: "バスケットボールをする" },
      { name: "バレーボールをする" },
      { name: "ストリートバスケットボールをする" }
    ],
  });
}