import { MatchingType, PrismaClient } from "@prisma/client";

export default async function seedMatchings(prisma: PrismaClient) {
	await prisma.matching.createMany({
		data: [
			{
				ownerId: 2,
				address: '123 Nguyen Van A Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-15T09:30:00'),
				desiredFood: 'Pho bo mam tom',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '123 Bui Thi Xuan Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T08:30:00'),
				desiredFood: 'Pho bo mam tom',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '12 Ly Thuong Kiet Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T08:35:00'),
				desiredFood: 'Cha ca',
				conversationTopics: 'Movie',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '53 Quan Xu Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T08:40:00'),
				desiredFood: 'Ga Quay',
				conversationTopics: 'Sport',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '35 Kim Mã Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T08:45:00'),
				desiredFood: 'Che Buoi',
				conversationTopics: 'Soccer',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '45 Kim Mã Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T08:50:00'),
				desiredFood: 'Banh Mi',
				conversationTopics: 'The Final of Champion League',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '85 Ta Quang Buu Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T08:55:00'),
				desiredFood: 'Pho bo mam tom',
				conversationTopics: 'Onepiece',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '67 Nguyen Tat Thanh Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T09:00:00'),
				desiredFood: 'Pho bo mam tom',
				conversationTopics: 'Tran Thanh',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '92 Hoang Mai Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T09:05:00'),
				desiredFood: 'Bun Cha',
				conversationTopics: 'Rap Viet Season 3',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '42 Nguyen Huu Canh Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T09:10:00'),
				desiredFood: 'Lon Quay',
				conversationTopics: 'Volleyball',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '75 Bui Thi Xuan Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T09:15:00'),
				desiredFood: 'Banh Xeo',
				conversationTopics: 'Tennis',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '65 Lac Trung Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T09:20:00'),
				desiredFood: 'Bun Ca',
				conversationTopics: 'Shopping',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '48 Xuan Dieu Street, Da Nang City',
				matchingDate: new Date('2023-06-06T09:25:00'),
				desiredFood: 'Com Rang',
				conversationTopics: 'Makeup',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '43 Tran Hung Dao Street, Hue City',
				matchingDate: new Date('2023-06-06T09:30:00'),
				desiredFood: 'Bun Bo',
				conversationTopics: 'Share about life',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '37 Kim Nguu Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T09:35:00'),
				desiredFood: 'Thit Lon Quay',
				conversationTopics: 'Politics',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '58 Nguyen Trai Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T09:40:00'),
				desiredFood: 'Bun Dau Mam Tom',
				conversationTopics: 'Math',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '73 Xuan Dieu Street, Da Nang City',
				matchingDate: new Date('2023-06-06T09:45:00'),
				desiredFood: 'Pho Ga',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '64 30-4 Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T09:50:00'),
				desiredFood: 'Com Tam',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '18 8-3 Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T09:55:00'),
				desiredFood: 'Buffet',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '13 De La Thanh Street, Ha Noi City',
				matchingDate: new Date('2023-06-06T10:00:00'),
				desiredFood: 'Pho Bat Da',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			},
			{
				ownerId: 2,
				address: '454 Nguyen Van Troi Street, Ho Chi Minh City',
				matchingDate: new Date('2023-06-06T10:05:00'),
				desiredFood: 'Bun Ca Cham',
				conversationTopics: 'The Impact of Artificial Intelligence on Society',
				matchingType: MatchingType.YOTEI,
			}
		]
	})
}